/**
 * libcss/shell — generateBootstrap
 *
 * Produces a complete bash bootstrap script from a config object.
 * The output is a string you can write to a .sh file.
 */
import type { ShellBootstrapConfig, PromptConfig, BannerConfig } from './types';

const DEFAULT_ALIASES: Record<string, string> = {
  cls: 'clear',
  '..': 'cd ..',
  '...': 'cd ../..',
  mkdir: 'mkdir -pv',
  ls: 'ls --color=auto',
  grep: 'grep --color=auto',
  ll: 'ls -alF --color=auto',
  la: 'ls -A --color=auto',
};

function bannerBox(name: string, version: string, cfg: Required<BannerConfig>): string {
  const label = `${cfg.icon}  ${name} v${version}`;
  const inner = label.length + 4;
  const top = '╭' + '─'.repeat(inner) + '╮';
  const mid = `│   ${label}   │`;
  const btm = '╰' + '─'.repeat(inner) + '╯';
  return [
    `echo -e "\\033[${cfg.color}m"`,
    `echo "  ${top}"`,
    `echo "  ${mid}"`,
    `echo "  ${btm}"`,
    `echo -e "\\033[0m"`,
  ].join('\n');
}

function bannerZigzag(name: string, version: string, cfg: Required<BannerConfig>): string {
  const zig = '╱╲'.repeat(18);
  const zag = '╲╱'.repeat(18);
  return [
    `echo -e "\\033[${cfg.color}m"`,
    `echo "  ${zig}"`,
    `echo -e "  \\033[${cfg.nameColor}m${cfg.icon}  ${name} v${version}\\033[${cfg.color}m"`,
    `echo "  ${zag}"`,
    `echo -e "\\033[0m"`,
  ].join('\n');
}

function bannerMinimal(name: string, version: string, cfg: Required<BannerConfig>): string {
  return [
    `echo -e "\\033[${cfg.nameColor}m${cfg.icon}  ${name} v${version}\\033[0m"`,
    `echo ""`,
  ].join('\n');
}

function generateBanner(name: string, version: string, cfg: BannerConfig = {}): string {
  const resolved: Required<BannerConfig> = {
    style: cfg.style ?? 'box',
    color: cfg.color ?? '1;36',
    nameColor: cfg.nameColor ?? cfg.color ?? '1;36',
    icon: cfg.icon ?? '☁',
  };

  switch (resolved.style) {
    case 'zigzag':
      return bannerZigzag(name, version, resolved);
    case 'minimal':
      return bannerMinimal(name, version, resolved);
    case 'none':
      return '';
    default:
      return bannerBox(name, version, resolved);
  }
}

function generatePrompt(cfg: PromptConfig = {}): string {
  const user = cfg.username ?? '\\u';
  const host = cfg.hostname ?? 'shell';
  const hc = cfg.hostColor ?? '1;32';
  const pc = cfg.pathColor ?? '1;34';
  const gc = cfg.gitColor ?? '33';
  const git = cfg.showGit !== false ? `\\[\\e[${gc}m\\]$(__git_branch)` : '';

  if (cfg.twoLine) {
    return `export PS1='\\[\\e[${hc}m\\]${user}@${host}\\[\\e[0m\\]:\\[\\e[${pc}m\\]\\w${git}\\[\\e[0m\\]\\n\\$ '`;
  }
  return `export PS1='\\[\\e[${hc}m\\]${user}@${host}\\[\\e[0m\\]:\\[\\e[${pc}m\\]\\w${git}\\[\\e[0m\\]\\$ '`;
}

const GIT_HELPER = `
__git_branch() {
  local branch
  branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
  if [ -n "$branch" ]; then
    local dirty=""
    if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
      dirty="*"
    fi
    echo " ($branch$dirty)"
  fi
}`.trim();

export function generateBootstrap(config: ShellBootstrapConfig): string {
  const version = config.appVersion ?? '1.0.0';
  const historySize = config.historySize ?? 10000;
  const mergedAliases = { ...DEFAULT_ALIASES, ...(config.aliases ?? {}) };

  const sections: string[] = [];

  // Header
  sections.push(`#!/usr/bin/env bash
# ${config.appName} — Shell Bootstrap
# Generated by libcss/shell scaffold`);

  // History
  sections.push(`
shopt -s histappend
shopt -s cmdhist
HISTSIZE=${historySize}
HISTFILESIZE=${historySize * 2}
HISTCONTROL=ignoreboth
export PROMPT_COMMAND="history -a; \${PROMPT_COMMAND:-}"`);

  // Shell options
  sections.push(`
shopt -s checkwinsize
shopt -s globstar 2>/dev/null
shopt -s autocd 2>/dev/null
shopt -s cdspell`);

  // Color support
  if (config.colorSupport !== false) {
    sections.push(`
export CLICOLOR=1
export TERM=xterm-256color

if command -v dircolors &>/dev/null; then
  eval "$(dircolors -b)"
fi`);
  }

  // Git prompt helper
  if (config.gitPrompt !== false) {
    sections.push(`
${GIT_HELPER}`);
  }

  // Prompt
  sections.push(`
${generatePrompt(config.prompt)}`);

  // Aliases
  const aliasLines = Object.entries(mergedAliases)
    .map(([name, cmd]) => `alias ${name}='${cmd}'`)
    .join('\n');
  sections.push(`
${aliasLines}`);

  // Welcome banner
  const banner = generateBanner(config.appName, version, config.banner);
  if (banner) {
    sections.push(`
${banner}`);
  }

  // Extra lines
  if (config.extraLines?.length) {
    sections.push(`
${config.extraLines.join('\n')}`);
  }

  return sections.join('\n') + '\n';
}
